# Generated by Django 2.1.7 on 2019-03-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20190313_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='users',
            new_name='user',
        ),
    ]
